version: '3.4'

services:
  jac.aeronaves:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  jac.embarque:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  jac.tripulantes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

